name: Build ESP32 Testing Pack

on:
  workflow_call:
    inputs:
      board:
        required: true
        type: string

#on: [push]
        
jobs:
  build-esp32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build base
        id: base
        uses: ./.github/actions/setup-base

      - name: Build ESP32
        run: bin/build-esp32.sh ${{ inputs.board }}

      - name: Get release version string
        shell: bash
        run: echo "version=$(./bin/buildinfo.py long)" >> $GITHUB_OUTPUT
        id: version

      - name: Store binaries as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ inputs.board }}-${{ steps.version.outputs.version }}.zip
          path: |
            release/*.bin
